# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-Bond-Find
version:      0.23
version_from: Find.pm
installdirs:  site
requires:
    Chemistry::Mol:                0.24

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
